### ISSUE TITLE
multiline editor can not move the cursor to end of line.

### ISSUE THREAD

**Issue by incity** [lvgl/lv_examples#60] opened 2020-06-01 02:11 UTC
![image](https://user-images.githubusercontent.com/7846605/83369826-1c453e80-a3f0-11ea-9607-f478e05488f3.png)

As shown in the figure, i can't move the cursor to the end of line use mouse click.

**Comment by incity** [comment] 2020-06-01 02:16
1. type anyone character, e.g. "a", and the cursor now is after "a", like this -> "a|"
2. click the editor, the cursor will move back, becomes  --> "|a"

**Comment by kisvegabor** [comment] 2020-06-01 20:29
@incity I've fixed it in `master`.

**Comment by incity** [comment] 2020-06-02 01:16
@kisvegabor not soloved, still have other same problems

**Comment by kisvegabor** [comment] 2020-06-02 05:14
Oh, really. There was a special case when BIDI was enabled and you clicked after the last character.
Should work now.

**Comment by incity** [comment] 2020-06-02 05:47
Hi still has other problems:
![image](https://user-images.githubusercontent.com/7846605/83484418-7967ef80-a4d7-11ea-9ba0-6f4f48263273.png)
click here before popup the keyboard, and it will auto input 'o'

**Comment by incity** [comment] 2020-06-02 05:50
![image](https://user-images.githubusercontent.com/7846605/83484679-0f9c1580-a4d8-11ea-8dc2-a9cad8c23087.png)

**Comment by incity** [comment] 2020-06-04 09:05
@kisvegabor did you see?

**Comment by kisvegabor** [comment] 2020-06-04 09:39
@incity 
The first issue (added "o" character) should be fixed here: https://github.com/lvgl/lv_examples/commit/5ac85f8faa472f7242a3591706d322219928e307

I can't reproduce the second one (can't open the keyboard again).
Can you send a video or gif?

**Comment by incity** [comment] 2020-06-05 02:04
[fb5baecb8b19b887b0b8d59cf5ad1fb4.zip](https://github.com/lvgl/lv_examples/files/4733520/fb5baecb8b19b887b0b8d59cf5ad1fb4.zip)
@kisvegabor

**Comment by kisvegabor** [comment] 2020-06-05 08:11
Fixed it, thank you!

**Closed** 2020-06-05 08:17 UTC
